//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
    public partial class OlsFault
    {
        
        private Response errorCodeField;
        
        private string mainErrorTextField;
        
        private string subErrorTextField;
        
        private FaultSeverityEnum severityField;
        
        private bool severityFieldSpecified;
        
        private string faultIdField;
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Response errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mainErrorText
        {
            get
            {
                return this.mainErrorTextField;
            }
            set
            {
                this.mainErrorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subErrorText
        {
            get
            {
                return this.subErrorTextField;
            }
            set
            {
                this.subErrorTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FaultSeverityEnum severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool severitySpecified
        {
            get
            {
                return this.severityFieldSpecified;
            }
            set
            {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string faultId
        {
            get
            {
                return this.faultIdField;
            }
            set
            {
                this.faultIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeStampSpecified
        {
            get
            {
                return this.timeStampFieldSpecified;
            }
            set
            {
                this.timeStampFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
    public partial class Response
    {
        
        private string mainCodeField;
        
        private string subCodeField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mainCode
        {
            get
            {
                return this.mainCodeField;
            }
            set
            {
                this.mainCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string subCode
        {
            get
            {
                return this.subCodeField;
            }
            set
            {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime timeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
    public enum FaultSeverityEnum
    {
        
        /// <remarks/>
        INFO,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FATAL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticate/", ConfigurationName="AuthenticationServiceReference.AuthenticationService")]
    public interface AuthenticationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:authenticate", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:authenticate", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.authenticateResponse> authenticateAsync(AuthenticationServiceReference.authenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:updatePassword" +
            "", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:updatePassword" +
            "", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.updatePasswordResponse> updatePasswordAsync(AuthenticationServiceReference.updatePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:updateSecurity" +
            "Questions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:updateSecurity" +
            "Questions", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.updateSecurityQuestionsResponse> updateSecurityQuestionsAsync(AuthenticationServiceReference.updateSecurityQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:getSecurityQue" +
            "stions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:getSecurityQue" +
            "stions", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.getSecurityQuestionsResponse> getSecurityQuestionsAsync(AuthenticationServiceReference.getSecurityQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:acceptTermsAnd" +
            "Conditions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:acceptTermsAnd" +
            "Conditions", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.acceptTermsAndConditionsResponse> acceptTermsAndConditionsAsync(AuthenticationServiceReference.acceptTermsAndConditionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:resetPassword", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:resetPassword", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.resetPasswordResponse> resetPasswordAsync(AuthenticationServiceReference.resetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:logout", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:logout", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.logoutResponse> logoutAsync(AuthenticationServiceReference.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:validateSecuri" +
            "tyQuestions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:validateSecuri" +
            "tyQuestions", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.validateSecurityQuestionsResponse> validateSecurityQuestionsAsync(AuthenticationServiceReference.validateSecurityQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:setupUserAccou" +
            "nt", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuthenticationServiceReference.OlsFault), Action="http://provider.model.service.ols.cqc.org.uk/AuthenticationService:setupUserAccou" +
            "nt", Name="olsFault", Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationServiceReference.setupUserAccountResponse> setupUserAccountAsync(AuthenticationServiceReference.setupUserAccountRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
    public partial class Credentials
    {
        
        private string tokenIdField;
        
        private string originatingSystemField;
        
        private string originatingSystemIdField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tokenId
        {
            get
            {
                return this.tokenIdField;
            }
            set
            {
                this.tokenIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string originatingSystem
        {
            get
            {
                return this.originatingSystemField;
            }
            set
            {
                this.originatingSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string originatingSystemId
        {
            get
            {
                return this.originatingSystemIdField;
            }
            set
            {
                this.originatingSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class authenticateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public string userType;
        
        public authenticateRequest()
        {
        }
        
        public authenticateRequest(AuthenticationServiceReference.Credentials Credentials, string userName, string password, string userType)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.password = password;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class authenticateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string tokenId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public bool isUpdatePasswordRequired;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public bool isSecurityQuestionsAnswered;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=3)]
        public string tandCVersionNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=4)]
        public string txnStatus;
        
        public authenticateResponse()
        {
        }
        
        public authenticateResponse(string tokenId, bool isUpdatePasswordRequired, bool isSecurityQuestionsAnswered, string tandCVersionNumber, string txnStatus)
        {
            this.tokenId = tokenId;
            this.isUpdatePasswordRequired = isUpdatePasswordRequired;
            this.isSecurityQuestionsAnswered = isSecurityQuestionsAnswered;
            this.tandCVersionNumber = tandCVersionNumber;
            this.txnStatus = txnStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdatePasswordRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class updatePasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public string oldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public string newPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=3)]
        public string userType;
        
        public updatePasswordRequest()
        {
        }
        
        public updatePasswordRequest(AuthenticationServiceReference.Credentials Credentials, string userName, string oldPassword, string newPassword, string userType)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdatePasswordResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class updatePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public updatePasswordResponse()
        {
        }
        
        public updatePasswordResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema")]
    public partial class SecuriyQAsData
    {
        
        private string questionField;
        
        private string answerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string question
        {
            get
            {
                return this.questionField;
            }
            set
            {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdateSecurityQuestionsRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class updateSecurityQuestionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AuthenticationServiceReference.SecuriyQAsData[] listOfSecurityQAs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public string userType;
        
        public updateSecurityQuestionsRequest()
        {
        }
        
        public updateSecurityQuestionsRequest(AuthenticationServiceReference.Credentials Credentials, string userName, AuthenticationServiceReference.SecuriyQAsData[] listOfSecurityQAs, string userType)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.listOfSecurityQAs = listOfSecurityQAs;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdateSecurityQuestionsResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class updateSecurityQuestionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public updateSecurityQuestionsResponse()
        {
        }
        
        public updateSecurityQuestionsResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema")]
    public partial class GetSecuriyQAsData
    {
        
        private string questionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string question
        {
            get
            {
                return this.questionField;
            }
            set
            {
                this.questionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityQuestionsRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class getSecurityQuestionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public string userType;
        
        public getSecurityQuestionsRequest()
        {
        }
        
        public getSecurityQuestionsRequest(AuthenticationServiceReference.Credentials Credentials, string userName, string userType)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityQuestionsResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class getSecurityQuestionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SecuriyQAsData", IsNullable=false)]
        public AuthenticationServiceReference.GetSecuriyQAsData[] listOfSecurityQAs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public string txnStatus;
        
        public getSecurityQuestionsResponse()
        {
        }
        
        public getSecurityQuestionsResponse(AuthenticationServiceReference.GetSecuriyQAsData[] listOfSecurityQAs, string txnStatus)
        {
            this.listOfSecurityQAs = listOfSecurityQAs;
            this.txnStatus = txnStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAcceptTermsAndConditionsRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class acceptTermsAndConditionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public string tnCVersion;
        
        public acceptTermsAndConditionsRequest()
        {
        }
        
        public acceptTermsAndConditionsRequest(AuthenticationServiceReference.Credentials Credentials, string userName, string tnCVersion)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.tnCVersion = tnCVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAcceptTermsAndConditionsResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class acceptTermsAndConditionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public acceptTermsAndConditionsResponse()
        {
        }
        
        public acceptTermsAndConditionsResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResetPasswordRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class resetPasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AuthenticationServiceReference.SecuriyQAsData[] listOfSecurityQAs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public bool isSecQuestionMandatory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=3)]
        public string userType;
        
        public resetPasswordRequest()
        {
        }
        
        public resetPasswordRequest(AuthenticationServiceReference.Credentials Credentials, string userName, AuthenticationServiceReference.SecuriyQAsData[] listOfSecurityQAs, bool isSecQuestionMandatory, string userType)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.listOfSecurityQAs = listOfSecurityQAs;
            this.isSecQuestionMandatory = isSecQuestionMandatory;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResetPasswordResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class resetPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public resetPasswordResponse()
        {
        }
        
        public resetPasswordResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLogOutRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class logoutRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string tokenId;
        
        public logoutRequest()
        {
        }
        
        public logoutRequest(AuthenticationServiceReference.Credentials Credentials, string tokenId)
        {
            this.Credentials = Credentials;
            this.tokenId = tokenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLogOutResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class logoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public logoutResponse()
        {
        }
        
        public logoutResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValidateSecurityQuestionsRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class validateSecurityQuestionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public AuthenticationServiceReference.SecuriyQAsData[] listOfSecurityQAs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public string userType;
        
        public validateSecurityQuestionsRequest()
        {
        }
        
        public validateSecurityQuestionsRequest(AuthenticationServiceReference.Credentials Credentials, string userName, AuthenticationServiceReference.SecuriyQAsData[] listOfSecurityQAs, string userType)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.listOfSecurityQAs = listOfSecurityQAs;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetValidateSecurityQuestionsResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class validateSecurityQuestionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public validateSecurityQuestionsResponse()
        {
        }
        
        public validateSecurityQuestionsResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema")]
    public partial class AccountSetUpUpdatePasswordRequest
    {
        
        private string oldPasswordField;
        
        private string newPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string oldPassword
        {
            get
            {
                return this.oldPasswordField;
            }
            set
            {
                this.oldPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string newPassword
        {
            get
            {
                return this.newPasswordField;
            }
            set
            {
                this.newPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema")]
    public partial class AccountSetUpUpdateSQRequest
    {
        
        private SecuriyQAsData[] listOfSecurityQAsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SecuriyQAsData[] listOfSecurityQAs
        {
            get
            {
                return this.listOfSecurityQAsField;
            }
            set
            {
                this.listOfSecurityQAsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema")]
    public partial class AccountSetUpAcceptTcRequest
    {
        
        private string tnCVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tnCVersion
        {
            get
            {
                return this.tnCVersionField;
            }
            set
            {
                this.tnCVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountSetUpRequest", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class setupUserAccountRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/masterdata")]
        public AuthenticationServiceReference.Credentials Credentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=1)]
        public string userType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=2)]
        public bool updatePasswordRequired;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=3)]
        public bool updateSecQRequired;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=4)]
        public bool acceptTNCRequired;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=5)]
        public AuthenticationServiceReference.AccountSetUpUpdatePasswordRequest accountSetUpUpdatePasswordRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=6)]
        public AuthenticationServiceReference.AccountSetUpUpdateSQRequest accountSetUpUpdateSQRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=7)]
        public AuthenticationServiceReference.AccountSetUpAcceptTcRequest accountSetUpAcceptTcRequest;
        
        public setupUserAccountRequest()
        {
        }
        
        public setupUserAccountRequest(AuthenticationServiceReference.Credentials Credentials, string userName, string userType, bool updatePasswordRequired, bool updateSecQRequired, bool acceptTNCRequired, AuthenticationServiceReference.AccountSetUpUpdatePasswordRequest accountSetUpUpdatePasswordRequest, AuthenticationServiceReference.AccountSetUpUpdateSQRequest accountSetUpUpdateSQRequest, AuthenticationServiceReference.AccountSetUpAcceptTcRequest accountSetUpAcceptTcRequest)
        {
            this.Credentials = Credentials;
            this.userName = userName;
            this.userType = userType;
            this.updatePasswordRequired = updatePasswordRequired;
            this.updateSecQRequired = updateSecQRequired;
            this.acceptTNCRequired = acceptTNCRequired;
            this.accountSetUpUpdatePasswordRequest = accountSetUpUpdatePasswordRequest;
            this.accountSetUpUpdateSQRequest = accountSetUpUpdateSQRequest;
            this.accountSetUpAcceptTcRequest = accountSetUpAcceptTcRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountSetUpResponse", WrapperNamespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", IsWrapped=true)]
    public partial class setupUserAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://provider.model.service.ols.cqc.org.uk/authenticateSchema", Order=0)]
        public string txnStatus;
        
        public setupUserAccountResponse()
        {
        }
        
        public setupUserAccountResponse(string txnStatus)
        {
            this.txnStatus = txnStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface AuthenticationServiceChannel : AuthenticationServiceReference.AuthenticationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<AuthenticationServiceReference.AuthenticationService>, AuthenticationServiceReference.AuthenticationService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationServiceClient() : 
                base(AuthenticationServiceClient.GetDefaultBinding(), AuthenticationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AuthenticateServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationServiceClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.authenticateResponse> authenticateAsync(AuthenticationServiceReference.authenticateRequest request)
        {
            return base.Channel.authenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.updatePasswordResponse> updatePasswordAsync(AuthenticationServiceReference.updatePasswordRequest request)
        {
            return base.Channel.updatePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.updateSecurityQuestionsResponse> updateSecurityQuestionsAsync(AuthenticationServiceReference.updateSecurityQuestionsRequest request)
        {
            return base.Channel.updateSecurityQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.getSecurityQuestionsResponse> getSecurityQuestionsAsync(AuthenticationServiceReference.getSecurityQuestionsRequest request)
        {
            return base.Channel.getSecurityQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.acceptTermsAndConditionsResponse> acceptTermsAndConditionsAsync(AuthenticationServiceReference.acceptTermsAndConditionsRequest request)
        {
            return base.Channel.acceptTermsAndConditionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.resetPasswordResponse> resetPasswordAsync(AuthenticationServiceReference.resetPasswordRequest request)
        {
            return base.Channel.resetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.logoutResponse> logoutAsync(AuthenticationServiceReference.logoutRequest request)
        {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.validateSecurityQuestionsResponse> validateSecurityQuestionsAsync(AuthenticationServiceReference.validateSecurityQuestionsRequest request)
        {
            return base.Channel.validateSecurityQuestionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthenticationServiceReference.setupUserAccountResponse> setupUserAccountAsync(AuthenticationServiceReference.setupUserAccountRequest request)
        {
            return base.Channel.setupUserAccountAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticateServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticateServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://provider.model.service.ols.cqc.org.uk/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthenticationServiceClient.GetBindingForEndpoint(EndpointConfiguration.AuthenticateServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthenticationServiceClient.GetEndpointAddress(EndpointConfiguration.AuthenticateServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenticateServicePort,
        }
    }
}
